excluded:
  - scan_derived_data
  - fastlane
  - vendor
reporter: "xcode"
warning_threshold: 1000
opt_in_rules:
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - toggle_bool
  - overridden_super_call
type_name:
  excluded:
    - T
  allowed_symbols:
    - _Previews
identifier_name:
  excluded:
      - id
      - by
  allowed_symbols:
    - _body
