platform :ios, '6.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'OHAttributedLabel', '~> 3.4.1'
pod 'GCOLaunchImageTransition', '~> 0.9.1'
pod 'MBProgressHUD', '~> 0.7'
pod 'DTCoreText', '~> 1.6.4'
pod 'InAppSettingsKit', '~> 1.1'
pod 'SSKeychain', '~> 1.2.0'
pod 'ARChromeActivity'
pod 'ARKippsterActivity'
pod 'FontAwesomeIconFactory', '~> 1.2'
pod 'NNNetwork', :podspec => 'NNNetwork-temp.podspec'
pod 'OHAlertView', '~> 2.0.0'