platform :ios, '6.0'
pod 'AFNetworking'
pod 'OHAttributedLabel'
pod 'GCOLaunchImageTransition'
pod 'MBProgressHUD'
pod 'DTCoreText'
pod 'InAppSettingsKit'
pod 'SSKeychain'
pod 'ARChromeActivity'
pod 'ARKippsterActivity'
pod 'FontAwesomeIconFactory'
pod 'Tapstream'
pod 'NNNetwork', :podspec => 'https://raw.github.com/weiran/NNNetwork/master/NNNetwork.podspec'