# A list of devices you want to take the screenshots from
devices([
  "iPhone SE (2nd generation)",
  "iPhone 12 Pro"
  "iPhone 12 Pro Max",
  "iPad (8th generation)",
  "iPad Pro (11-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (4th generation)"
])

# The name of the scheme which contains the UI Tests
scheme("Hackers")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# workspace "../Hackers.xcworkspace"

# For more information about all available options run
# fastlane action snapshot
