# A list of devices you want to take the screenshots from
devices([
  "iPhone SE (3rd generation)",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone 8 Plus",
  "iPad (9th generation)",
  "iPad mini (6th generation)",
  "iPad Pro (11-inch) (3rd generation)",
  "iPad Pro (12.9-inch) (5th generation)"
])

# The name of the scheme which contains the UI Tests
scheme("Hackers")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# For more information about all available options run
# fastlane action snapshot
